services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - C:\Users\User\OneDrive\Escritorio\Greco\2023\Arquitectura de Software\DCpostgres:/var/lib/postgresql/data
    networks:
        - pmarquez-network
  currency-converter:
    image: demo:2.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\User\OneDrive\Escritorio\Greco\2023\Arquitectura de Software\Logs:/Users/User/OneDrive/Escritorio/Greco/2023/Arquitectura de Software/SpringDKLogs
    depends_on:
      - postgres
    networks:
        - pmarquez-network
  angular:
    image: angular-sofware:1.0.0
    ports:
      - "4200:80"
    volumes:
      - C:\Users\User\OneDrive\Escritorio\Greco\2023\Arquitectura de Software\Currency_change\CurrencyKTFront-main\nginx.conf:/etc/nginx/nginx.conf
    networks:
        - pmarquez-network

networks:
  pmarquez-network:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.14.0.0/16
              gateway: 172.14.0.1